codingjobs/apps/job/urls.py
from unicodedata import name
from django.urls import path,include
from .api import api_search
from .views import job_detail,add_job,apply_for_job,search,edit_job

urlpatterns=[
    path('api/search/',api_search,name='api_search'),
    path('search',search,name='search'),
    path('add/',add_job,name='add_job'),
    path('<int:job_id>/',job_detail,name='job_detail'),
    path('<int:job_id>/edit/',edit_job,name='edit_job'),
    path('<int:job_id>/apply_for_job/',apply_for_job,name="apply_for_job")
]

codingjobs/codingjobs/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth  import views

from apps.core.views import frontPage,signup
from apps.job.views import job_detail
from apps.job.views import add_job
from apps.userprofile.views import dashboard

urlpatterns = [
    path('',frontPage,name='frontpage'),
    path('signup/',signup,name='signup'),
    path('logout/',views.LogoutView.as_view(),name="logout"),
    path('login/',views.LoginView.as_view(template_name='core/login.html'),name="login"),
    path('admin/', admin.site.urls),
    path('dashboard/',include('apps.userprofile.urls')),
    path('notifications/',include('apps.notification.urls')),
    path('jobs/',include('apps.job.urls')),

    # path('jobs/add/',add_job,name='add_job'), 
    # path('jobs/<int:job_id>/',job_detail,name="job_detail"),
]

codingjobs/apps/job/models.py
from pyexpat import model
from tkinter import ACTIVE, CASCADE
from turtle import title
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Job(models.Model):
    SIZE_1_9='size_1_9'
    SIZE_10_49='size_10_49'
    SIZE_50_99='size_50_99'
    SIZE_100='size_100'

    CHOICES_SIZE=(
        (SIZE_1_9,'1_9'),
        (SIZE_10_49,'10_49'),
        (SIZE_50_99,'50_99'),
        (SIZE_100,'100+')
    )
    ACTIVE='active'
    EMPLOYED='employed'
    ARCHIVED='archaived'
    
    CHOICES_STATUS=(
        (ACTIVE,'active'),
        (EMPLOYED,'employed'),
        (ARCHIVED,'archaived')
    )

    title=models.CharField(max_length=250)
    short_description=models.TextField()
    long_description=models.TextField(blank=True,null=True)

    company_name=models.CharField(max_length=225)
    company_address=models.CharField(max_length=225,blank=True,null=True)
    company_zipcode=models.CharField(max_length=225,blank=True,null=True)
    company_place=models.CharField(max_length=225,blank=True,null=True)
    company_country=models.CharField(max_length=225,blank=True,null=True)
    company_size=models.CharField(max_length=20,choices=CHOICES_SIZE,default=SIZE_1_9)

    created_by=models.ForeignKey(User,related_name='jobs',on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    changed_at=models.DateTimeField(auto_now=True)
    
    status=models.CharField(max_length=20,choices=CHOICES_STATUS,default=ACTIVE)

    def __str__(self):
        return self.title

class Application(models.Model):
    job=models.ForeignKey(Job,related_name='applications',on_delete=models.CASCADE)
    content=models.TextField()
    experiance=models.TextField()

    created_by=models.ForeignKey(User,related_name='applications',on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)

codingjobs/apps/job/forms.py
from django import forms
from .models import Job,Application

class AddJobForm(forms.ModelForm):
    class Meta:
        model=Job
        fields=[
            'title',
            'short_description',
            'long_description',
            'company_name',
            'company_address',
            'company_zipcode',
            'company_place',
            'company_country',
            'company_size'
        ]

class ApplicationForm(forms.ModelForm):
    class Meta:
        model=Application
        fields=[
            'content',
            'experiance',
        ]

codingjobs/apps/job/views.py
import imp
from multiprocessing import context
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Job,Application
from .forms import AddJobForm,ApplicationForm
from apps.notification.utilities import create_notification
# Create your views here.

def search(request):
    return render(request,'job/search.html')

def job_detail(request,job_id):
    job=Job.objects.get(pk=job_id)
    context={'job':job}
    return render(request,'job/job_detail.html',context)

@login_required
def apply_for_job(request,job_id):
    context={}
    form=None
    job=Job.objects.get(pk=job_id)
     
    if request.method=='POST':
        form=ApplicationForm(request.POST)
        if form.is_valid():
            application=form.save(commit=False)
            application.job=job
            application.created_by=request.user
            application.save()
            
            create_notification(request,job.created_by,'application',extra_id=application.id)
            return redirect('dashboard')
        else:
            form=ApplicationForm()
    context={'form':form,'job':job}

    return render(request,'job/apply_for_job.html',context)

@login_required
def add_job(request):
    if request.method=="POST":
        form=AddJobForm(request.POST)

        if form.is_valid():
            job=form.save(commit=False)
            job.created_by=request.user
            job.save()
            
            return redirect('dashboard')
    else:
        form=AddJobForm()
    context={'form':form}
    return render(request,'job/add_job.html',context)


@login_required
def edit_job(request,job_id):
    job=get_object_or_404(Job,pk=job_id,created_by=request.user)
    if request.method=="POST":
        form=AddJobForm(request.POST,instance=job)

        if form.is_valid():
            job=form.save(commit=False)
            job.status=request.POST.get('status')
            job.save()
            
            return redirect('dashboard')
    else:
        form=AddJobForm(instance=job)
    context={'form':form,'job':job}
    return render(request,'job/edit_job.html',context)

codingjobs/apps/job/templates/job/add_job.html
{% extends 'core/base.html' %}
{% block content %}
<div id="add-job-app">


    <h1 class="title">Add jobs...</h1>
    <form action="." method="post" v-on:submit="validateForm">
        {% csrf_token %}
        <!-- {% if form.errors %}
        {% for error in form.errors %}
        <div class="notification is-danger">
            {{ error }}
        </div>
        {% endfor %}
        {% endif %} -->
        <div class="notification is-danger" v-if="errors.length>0">
            <p v-for="error in errors">
                [[ error ]]
            </p>
        </div>

        <div class="field">
            <label for="">title</label>
            <div class="control">
                <input class="input" type="text" name="title" id="id_title" v-model="title">
            </div>
        </div>

        <div class="field">
            <label for="">short description</label>
            <div class="control">
                <textarea class="textarea" name="short_description" type="text" name="title" id="id_short_description" v-model="short_description"></textarea>
            </div>
        </div>

        <div class="field">
            <label for="">long description</label>
            <div class="control">
                <textarea class="textarea" name="long_description" type="text" name="title" id="id_long _description" ></textarea>
            </div>
        </div>
        <div class="field">
            <label for="">company name</label>
            <div class="control">
                <input class="input" type="text" name="company_name" id="id_company_name" v-model="company_name">
            </div>
        </div>
        <div class="field">
            <label for="">company address</label>
            <div class="control">
                <input class="input" type="text" name="company_address" id="id_company_address">
            </div>
        </div>
        <div class="field">
            <label for="">company zipcode</label>
            <div class="control">
                <input class="input" type="text" name="company_zipcode" id="id_company_zipcode">
            </div>
        </div>
        <div class="field">
            <label for="">company place</label>
            <div class="control">
                <input class="input" type="text" name="company_place" id="id_company_place">
            </div>
        </div>
        <div class="field">
            <label for="">company country</label>
            <div class="control">
                <input class="input" type="text" name="company_country" id="id_company_country">
            </div>
        </div>
        <div class="field">
            <label for="">company size</label>
            <div class="control">
                <div class="select">
                    <select name="company_size" v-model="company_size">
                        <option value="">choose size</option>
                        <option value="size_1_9">1-9</option>
                        <option value="size_10_49">10-49</option>
                        <option value="size_50_99">50-99</option>
                        <option value="size_100">100+</option>
                    </select>
                </div>
            </div>
        </div>

        <div class="field">
            <div class="control">
                <button class="button is-success">Submit</button>
            </div>
        </div>
    </form>

</div>

{% endblock content %}

{% block scripts %}
<script>
    const AddJobApp={
        data(){
            return{
                title:'',
                company_name:'',
                short_description:'',
                company_size:'',
                errors:[]
            }
        },
        delimiters:['[[',']]'],
        methods:{
            validateForm(e){
                this.errors=[]
                if(this.title===''){
                    this.errors.push('the title field is missing')
                }
                if(this.short_description===''){
                    this.errors.push('the short_description field is missing')
                }
                if(this.company_name===''){
                    this.errors.push('the company_name field is missing')
                }
                if(this.company_size===''){
                    this.errors.push('the company_size field is missing')
                }
                if(this.errors.length){
                    e.prevenDefault()
                    return false
                }
                else{
                    return true
                }
            }
        }

    }
    Vue.createApp(AddJobApp).mount('#add-job-app');
</script>

{% endblock %}

codingjobs/apps/job/templates/job/apply_for_job.html
{% extends 'core/base.html' %}
{% block content %}

<h1 class="title">apply for job- {{ job.title }} </h1>
<form action="." method="post">
    {% csrf_token %}
    {% if form.errors %}
    {% for error in form.errors %}
    <div class="notification is-danger">
        {{ error }}
    </div>
    {% endfor %}
    {% endif %}
    <div class="field">
        <label for="">Content</label>
        <div class="control">
            <textarea class="textarea" name="content" type="text" name="title" id="id_content"></textarea>
        </div>
    </div>

    <div class="field">
        <label for="">experiance</label>
        <div class="control">
            <textarea class="textarea" name="experiance" type="text" name="title" id="id_experiance"></textarea>
        </div>
    </div>

    <div class="field">
        <div class="control">
            <button class="button is-success">Submit</button>
        </div>
    </div>
</form>

{% endblock content %}

codingjobs/apps/job/templates/job/edit_job.html
{% extends 'core/base.html' %}
{% block content %}
<div id="edit-job-app">


    <h1 class="title">Edit jobs...</h1>
    <form action="." method="post" v-on:submit="validateForm">
        {% csrf_token %}
        <!-- {% if form.errors %}
        {% for error in form.errors %}
        <div class="notification is-danger">
            {{ error }}
        </div>
        {% endfor %}
        {% endif %} -->
        <div class="notification is-danger" v-if="errors.length>0">
            <p v-for="error in errors">
                [[ error ]]
            </p>
        </div>

        <div class="field">
            <label for="">title</label>
            <div class="control">
                <input class="input" type="text" name="title" id="id_title" v-model="title">
            </div>
        </div>

        <div class="field">
            <label for="">short description</label>
            <div class="control">
                <textarea class="textarea" name="short_description" type="text" name="title" id="id_short_description" v-model="short_description"></textarea>
            </div>
        </div>

        <div class="field">
            <label for="">long description</label>
            <div class="control">
                <textarea class="textarea" name="long_description" type="text" name="title" id="id_long_description" >{% if job.long_description %} {{ job.long_description }} {% endif %}</textarea>
            </div>
        </div>
        <div class="field">
            <label for="">company name</label>
            <div class="control">
                <input class="input" type="text" name="company_name" id="id_company_name" v-model="company_name">
            </div>
        </div>
        <div class="field">
            <label for="">company address</label>
            <div class="control">
                <input class="input" type="text" name="company_address" id="id_company_address" value="{% if job.company_address %} {{ job.company_address }} {% endif %}">
            </div>
        </div>
        <div class="field">
            <label for="">company zipcode</label>
            <div class="control">
                <input class="input" type="text" name="company_zipcode" id="id_company_zipcode" value="{% if job.company_zipcode %} {{ job.company_zipcode }} {% endif %}">
            </div>
        </div>
        <div class="field">
            <label for="">company place</label>
            <div class="control">
                <input class="input" type="text" name="company_place" id="id_company_place" value="{% if job.company_place %} {{ job.company_place }} {% endif %}">
            </div>
        </div>
        <div class="field">
            <label for="">company country</label>
            <div class="control">
                <input class="input" type="text" name="company_country" id="id_company_country" value="{% if job.company_country %} {{ job.company_country }} {% endif %}">
            </div>
        </div>
        <div class="field">
            <label for="">company size</label>
            <div class="control">
                <div class="select">
                    <select name="company_size" v-model="company_size">
                        <option value="">choose size</option>
                        <option value="size_1_9">1-9</option>
                        <option value="size_10_49">10-49</option>
                        <option value="size_50_99">50-99</option>
                        <option value="size_100">100+</option>
                    </select>
                </div>
            </div>
        </div>

        
        <div class="field">
            <label for="">Status</label>
            <div class="control">
                <div class="select">
                    <select name="status">
                        <option value="active" {% if job.status == 'active' %} selected {% endif %}>Active</option>
                        <option value="employed" {% if job.status == 'employed' %} selected {% endif %}>employed</option>
                        <option value="archaived" {% if job.status == 'archaived' %} selected {% endif %}>archaived</option>
                    </select>
                </div>
            </div>
        </div>

        <div class="field">
            <div class="control">
                <button class="button is-success">save changes</button>
            </div>
        </div>
    </form>

</div>

{% endblock content %}

{% block scripts %}
<script>
    const EditJobApp={
        data(){
            return{
                title:'{{ job.title }}',
                company_name:'{{ job.company_name }}',
                short_description:'{{ job.short_description }}',
                company_size:'{{ job.company_size }}',
                errors:[]
            }
        },
        delimiters:['[[',']]'],
        methods:{
            validateForm(e){
                this.errors=[]
                if(this.title===''){
                    this.errors.push('the title field is missing')
                }
                if(this.short_description===''){
                    this.errors.push('the short_description field is missing')
                }
                if(this.company_name===''){
                    this.errors.push('the company_name field is missing')
                }
                if(this.company_size===''){
                    this.errors.push('the company_size field is missing')
                }
                if(this.errors.length){
                    e.prevenDefault()
                    return false
                }
                else{
                    return true
                }
            }
        }

    }
    Vue.createApp(EditJobApp).mount('#edit-job-app');
</script>

{% endblock %}

codingjobs/apps/job/templates/job/job_detail.html
{% extends 'core/base.html' %}
{% block content %}
<h1 class="title">{{ job.title }}--{{ job.get_status_display }}</h1>
<p class="is-size-4">{{ job.short_description }}</p>
<p>{{ job.long_description }}</p>
<b>company name:</b>{{ job.company_name }} <br>

{% if job.company_address %} <b>company address:</b>{{ job.company_address }} <br>{% endif %}
{% if job.company_zipcode %} <b>company zipcode:</b>{{ job.company_zipcode }} <br>{% endif %}
{% if job.company_place %} <b>company place:</b>{{ job.company_place }} <br>{% endif %}
{% if job.company_country %} <b>company country:</b>{{ job.company_country}} <br>{% endif %}
<b>company size:</b>{{ job.get_company_size_display }} <br>
{% if job.status == 'active' %}
    <a class="button is-success" href="{% url 'apply_for_job' job.id %}">Apply</a>
{% else %}
    <p>this job is not available</p>
{% endif %}

{% endblock content %}

codingjobs/apps/job/templates/job/search.html
{% extends 'core/base.html' %}
{% block content %}
<div id="search-app">
    <h1 class="title">Search</h1>
    <form v-on:submit.prevent ="performSearch()">
        <div class="columns">
            <div class="column is-4">
                <div class="field">
                    <label for="">Query</label>
                    <div class="control">
                        <input type="text" name="query" class="input" v-model="query">
                    </div>
                </div>
                <div class="field">
                    <label for="">company size</label>
                    <div class="control">
                        <div class="select">
                            <select name="company_size" v-model="company_size"> 
                                <option value="" selected>All</option>
                                <option value="size_1_9">1-9</option>
                                <option value="size_10_49">10-49</option>
                                <option value="size_50_99">50-99</option>
                                <option value="size_100">100+</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <button class="button is-success">search</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <div v-if="jobs.length">
        <hr>
        <div
            v-for="job in jobs"  
            v-bind:key="job.id"
            class="notification mt-2">
            <h3 class="is-size-4">[[ job.title ]]</h3>
            <p>[[ job.company_name ]]</p>
            <a v-bind:href="job.url">view details</a>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script>
    const SearchApp={
        data(){
            return{
                query:'',
                company_size:'',
                jobs:[]
            }
        },
        delimiters:['[[',']]'],
        methods:{
            performSearch(){
                var data={
                    'query':this.query,
                    'company_size':this.company_size
                }
                fetch('/jobs/api/search/',{
                    method:'POST',
                    headers:{
                        'Content-Type':'application/json',
                        'X-CSRFToken':'{{ csrf_token }}'
                    },
                    body:JSON.stringify(data)

                }).then((response)=>{
                    return response.json()
                }).then((result)=>{
                    console.log(result.jobs)
                    this.jobs=result.jobs
                }).catch((error)=>{
                    console.log('error',error)
                })
            }
        }
        
    }
    Vue.createApp(SearchApp).mount('#search-app')
</script>

{% endblock scripts %}